name: Deploy website to Heroku
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # git clone
      - uses: actions/checkout@v2
      # linter
      - uses: michaelw90/PHP-Lint@master
      # security-checker
      - uses: symfonycorp/security-checker-action@v2
      # deploy
      - uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}